module.exports =
   device:  device  = require('./src/@device')
   math:    math    = require('./src/@math')
   util:    util    = require('./src/@util')
   Canvas:  Canvas  = require('./src/Canvas')
   Color:   Color   = require('./src/Color')
   Matrix:  Matrix  = require('./src/Matrix')
   Vector2: Vector2 = require('./src/Vector2')
   Vector3: Vector3 = require('./src/Vector3')
   Vector4: Vector4 = require('./src/Vector4')

   canvas: (args...) -> new @Canvas(args...)
   color:  (args...) -> new @Color(args...)
   mat:    (args...) -> new @Matrix(args...)
   vec2:   (args...) -> new @Vector2(args...)
   vec3:   (args...) -> new @Vector3(args...)
   vec4:   (args...) -> new @Vector4(args...)