module.exports =
   Canvas:  require('./src/Canvas')
   Color:   require('./src/Color')
   Color3:  require('./src/Color3')
   Color4:  require('./src/Color4')
   Vector:  require('./src/Vector')
   Vector2: require('./src/Vector2')
   Vector3: require('./src/Vector3')
   Vector4: require('./src/Vector4')
   device:  require('./src/device')
   math:    require('./src/math')

   canvas: (type)     -> document.createElement('canvas').init(type)
   color3: (args...)  -> new module.exports.Color3(args...)
   color4:  (args...) -> new module.exports.Color4(args...)
   vec2: (x, y)       -> new module.exports.Vector2(x, y)
   vec3: (x, y, z)    -> new module.exports.Vector3(x, y, z)
   vec4: (x, y, z, w) -> new module.exports.Vector4(x, y, z, w)