heap = new BinaryHeap()
   .add('data|90', 90)
   .add('data|80', 80)
   .add('data|85', 85)
   .add('data|86', 86)
   .add('data|87', 87)
   .add('data|112', 112)
   .add('data|115', 115)
   .add('data|109', 109)
   .add('data|800', 800)

console.log heap.top()
console.log heap.top()
console.log heap.top()
console.log heap.top()
console.log heap.top()
console.log heap.top()
console.log heap.top()
console.log heap.top()
console.log heap.top()
console.log heap.top()
console.log heap