console.log 'deg:',      Math.deg(Math.PI)
console.log 'rad:',      Math.rad(180)
console.log 'rand:',     Math.rand(0,100)
console.log 'rand_int:', Math.rand_int(0,100)
console.log 'ceil_2:',   Math.ceil_2(60)
console.log 'mix:',      Math.mix(100,200,0.5)