module.exports =
   device:   require('./device/@')
   math:     require('./math/@')
   renderer: require('./renderer/@')
   util:     require('./util/@')

   mat3:   (args...) -> new @math.Matrix3(args...)
   mat4:   (args...) -> new @math.Matrix4(args...)
   vec2:   (args...) -> new @math.Vector2(args...)
   vec3:   (args...) -> new @math.Vector3(args...)
   vec4:   (args...) -> new @math.Vector4(args...)
   canvas: (args...) -> new @renderer.Canvas(args...)
   shader: (args...) -> new @renderer.Shader(args...)
   clock:  (args...) -> new @util.Clock(args...)
   color:  (args...) -> new @util.Color(args...)
   bus:    (args...) -> new @util.MessageBus(args...)
   tween:  (args...) -> new @util.Tween(args...)