module.exports =
   device: require('./device/@')
   math:   require('./math/@')
   util:   require('./util/@')

   Matrix3:          require('./math/Matrix3')
   Matrix4:          require('./math/Matrix4')
   Vector2:          require('./math/Vector2')
   Vector3:          require('./math/Vector3')
   Vector4:          require('./math/Vector4')
   Canvas:           require('./renderer/Canvas')
   Shader:           require('./renderer/Shader')
   ProjectionOrtho2: require('./transform/ProjectionOrtho2')
   Rotation2:        require('./transform/Rotation2')
   Scaling2:         require('./transform/Scaling2')
   Translation2:     require('./transform/Translation2')
   Clock:            require('./util/Clock')
   Color:            require('./util/Color')
   EventBus:         require('./util/EventBus')
   Tween:            require('./util/Tween')

   mat3:   (args...) -> new @Matrix3(args...)
   mat4:   (args...) -> new @Matrix4(args...)
   vec2:   (args...) -> new @Vector2(args...)
   vec3:   (args...) -> new @Vector3(args...)
   vec4:   (args...) -> new @Vector4(args...)
   canvas: (args...) -> new @Canvas(args...)
   shader: (args...) -> new @Shader(args...)
   clock:  (args...) -> new @Clock(args...)
   color:  (args...) -> new @Color(args...)
   bus:    (args...) -> new @EventBus(args...)
   tween:  (args...) -> new @Tween(args...)